# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('min_nights', models.PositiveSmallIntegerField(verbose_name='Minimo de noites')),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteis',
            },
        ),
        migrations.AddField(
            model_name='disponibility',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibility', to='hotels.Hotel', verbose_name='Hotel'),
        ),
    ]
