# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibility',
            name='avaiable',
            field=models.BooleanField(default=False, verbose_name='Disponivel?'),
        ),
    ]
